config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'groups#index'

  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :members
  has_many :users, through: :members
  has_many :messages

  validates :group_name, presence: true

  def show_last_message
    if (last_message = messages.last).present?
      if last_message.body?
        last_message.body
      else
        "画像が投稿されています"
      end
    else
      "まだメッセージはありません"
    end
  end
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  mount_uploader :image, ImageUploader
  validates :body_or_image, presence: true
  def body_or_image
    body.present? || image.present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :messages
  has_many :members
  has_many :groups, through: :members
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
       devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]
  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:group_name, user_ids: [])
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
    respond_to do |format|
      format.html
      format.json{ @new_message = @messages.where('id > ?', params[:id])}
    end
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html{redirect_to group_messages_path(@group), notice: "メッセージが送信されました"}
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = "メッセージを入力してください"
      render 'index'
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group= Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%")
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/massages_controller_helper.rb
module MassagesControllerHelper
end

app/views/groups/_form.html.haml
= form_for (@group) do |f|
  - if @group.errors.any?
    .chat-group-form__errors
      %h2="#{@group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - @group.errors.full_messages.each do |message|
          %li = message
  %form#new_chat_group.new_chat_group{"accept-charset": :"UTF-8", action: "/chat_groups", method: "post"}
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{for: "chat_group_name"} グループ名
      .chat-group-form__field--right
        = f.text_field :group_name, class: "chat-group-form__input", placeholder: "グループ名を入力してください"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{for: "chat_group_チャットメンバーを追加"} チャットメンバーを追加
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          %input#user-search-field.chat-group-form__input{placeholder: "追加したいユーザー名を入力してください", type: "text", name: "keyword", value: ""}
        #user-search-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー
      .chat-group-form__field--right
        .chat-group-users
          .chat-group-user.clearfix.js-chat-member
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit class: 'chat-group-form__action-btn', value: 'Save'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group}

app/views/groups/index.html.haml
.wrapper
  = render 'shared/side_bar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', { group: @group}

app/views/layouts/_flash.html.haml
.flash
  - flash.each do |key, value|
    = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/flash'
    = yield

app/views/massages/_index.html.haml
.chat-main__body--messages-list
  .chat-main__body--massages-list--massage
    .chat-main__body--massages-list--massage-name
      kawashima
    .chat-main__body--massages-list--massage-time
      2018/02/12 19:38:00
    .chat-main__body--massages-list--massage-body
      aaaaaaa
.chat-main__body--messages-list
  .chat-main__body--massages-list--massage
    .chat-main__body--massages-list--massage-name
      iida
    .chat-main__body--massages-list--massage-time
      2018/02/12 19:39:00
    .chat-main__body--massages-list--massage-body
      aaaaaaa
    .chat-main__body--messages-list
.chat-main__body--massages-list--massage
  .chat-main__body--massages-list--massage-name
    kawashima
  .chat-main__body--massages-list--massage-time
    2018/02/13 19:39:00
  .chat-main__body--massages-list--massage-body
    oooooooooooooo

app/views/massages/index.html.haml
.wrapper
  %p.create-chatgroup
    チャットグループが作成されました。
  .chat-side
    .chat-side__user
      .chat-side__user-content
        .chat-side__user-name
          kawashima
          = link_to '/' do
            %i.fa.fa-cog.icon
          = link_to '/' do
            %i.fa.fa-edit.icon
    .chat-side__groups
      .groups-list
        .groups-list--group
          .groups-list--group-name
            america
          .groups-list--group-message
            USA USA
      .groups-list
        .groups-list--group
          .groups-list--group-name
            nippon
          .groups-list--group-message
            JPN JPN
  .chat-main
    .chat-main__header
      .chat-main__header--group
        .chat-main__header--group-name
          america
          %input.button{type: "button",name: "edit", value: "Edit"}
      .chat-main__header--member
        MEMBER: kawashima
    .chat-main__body
      = render partial: "message"
    .chat-main__footer
      %form.chat-main__footer--form
        %input.chat-main__footer--form-message{placeholder: "type a message"}
          %i.fa.fa-image.icon
        %input.chat-main__footer--input{type: "button", name: "send", value: "Send"}

app/views/messages/_message.html.haml
#target.messages-list{"data-message-id": "#{message.id}"}
  .messages-list--message
    .messages-list--message-name
      = message.user.name
    .messages-list--message-time
      = I18n.l(message.created_at)
  - if message.body.present?
    .messages-list--message-body
      = message.body
  - if message.image.present?
    = image_tag "#{message.image}", class: "img"

app/views/messages/index.html.haml
.wrapper
  = render 'shared/side_bar'
  .chat-main
    .chat-main__header
      .chat-main__header--group
        .chat-main__header--group-name
          = @group.group_name
          = link_to edit_group_path(@group) do
            %input.button{type: "button",name: "edit", value: "Edit"}
      .chat-main__header--member
        MEMBER:
        = @group.users.name
    #target.chat-main__body
      = render @messages
    .chat-main__footer
      = form_for [@group, @message], html: {class: 'chat-main__footer--form', id: "new_message"} do |f|
        = f.text_field :body, class: 'chat-main__footer--form-message', placeholder: 'type a message'
        = f.label :image, class: 'form__label' do
          %i.fa.fa-image
          = f.file_field :image, class: 'hidden'
          = f.submit type: "submit", name: "send", value: "Send", class: "chat-main__footer--input"

app/views/shared/_side_bar.html.haml
.chat-side
  .chat-side__user
    .chat-side__user-content
      .chat-side__user-name
        = current_user.name
        = link_to edit_user_path(current_user) do
          %i.fa.fa-cog.icon
        = link_to new_group_path(current_user) do
          %i.fa.fa-edit.icon
  .chat-side__groups
    - current_user.groups.each do |group|
      = link_to group_messages_path(group) do
        .groups-list
          .groups-list--group
            .groups-list--group-name
              = group.group_name
            .groups-list--group-message
              = group.show_last_message

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'